### ISSUE TITLE
suicide does not work

### ISSUE THREAD

**Issue by moosemilker** [salutesh/RealityGamingActionMenu#3]
suicide does not shot any in-game action

**Comment by salutesh** [comment]
Wrong, suicide is working very well, please read the hole release threat:
http://epochmod.com/forum/index.php?/topic/34187-action-menu-version-12-alpha-by-salutesh-inspired-by-it07/

**Comment by moosemilker** [comment]
I followed the exact installation steps and this failed... Test more dude.
